### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films filtered by minimum-duration
GET {{baseUrl}}/films?minimum-duration=119

### Read all films filtered by minimum-duration
GET {{baseUrl}}/films?minimum-duration=-1

### Read all films filtered by a prefix
GET {{baseUrl}}/films?title-starts-with=Harry

### Read all films filtered by a prefix
GET {{baseUrl}}/films?title-starts-with=HarryPoPoPOtter

### Read all films sorted by title ascending order
GET {{baseUrl}}/films?order=title

### Read all films sorted by title descending order
GET {{baseUrl}}/films?order=-title

### Get a film from the list
GET {{baseUrl}}/films/21

### Create a new film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title" : "Jurasic Parc",
    "duration" : 119,
    "budget" : 345000,
    "link" : "https://"
}

### Pagination system
GET {{baseUrl}}/films?page=2&limit=10